### ISSUE TITLE
Question: Why are worker threads still spawned?

### ISSUE THREAD

**Issue by Lothy** [StephenCleary/AsyncEx.Context#4]
Hi Stephen,

I don't know if you usually take questions here, but I figured I'd ask anyway.

I created the following code to play around with in the Visual Studio 2015 debugger:
https://gist.github.com/Lothy/0e0bd1fe482e675670886760c29c9c12

The context works in that all code resumes on the main thread. However I notice while debugging that, after awaiting a method such as Task.Delay(int), worker threads are created.
This screenshot demonstrates what I mean:
![asynccontextdebuggerscreenshots](https://cloud.githubusercontent.com/assets/650630/21975795/cb03e528-dc22-11e6-9431-836f797ca6ad.png)

Is there a reason that these threads are spawned when the MaximumConcurrencyLevel in your TaskScheduler implementation is set to 1?
Is there a way to control the spawning of these threads so that worker threads aren't spawned at all?

Thanks for your help, and have a great day!

Dan

**Comment by StephenCleary** [comment]
`AsyncContext` does not create any threads, nor does it use thread pool threads at all.

However, thread pool threads are *shared* under the hood by timers. There is one timer thread (for all timers) and another thread that is used to complete the task returned by `Task.Delay`. So, seeing a couple of threads added after a `Task.Delay` is normal. However, these threads are shared, so there won't be any *more* threads regardless of how many `Task.Delay`s your code has.

**Comment by Lothy** [comment]
Okay, brilliant.

Thank you for sharing your insight.
